#!/bin/bash

COMMAND=$1
PARAM1=$2
PARAM2=$3
PARAM3=$4
echo "Excuting for command: $COMMAND"

# node -e 'require("./prices.seed.js").create("newPrices")'

case "$COMMAND" in

'create')  echo "Creating a new database"
    echo $PARAM1
    node -e "require('./prices.seed.js').create('"$PARAM1"')"
    echo $CREATE
    ;;
'delete')  echo  "Deleting db"
    echo $PARAM1
    node -e "require('./prices.seed.js').remove('"$PARAM1"')"
    ;;
'getTables') 
    echo "Getting all avialable items"
    node -e "require('./prices.seed.js').getTables()"
    ;;
'putInBatch') 
    echo "Batch putting a data "
    node -e "require('./prices.seed.js').getTables()"
    ;;
'scan') 
    echo "Batch putting a data "
    node -e "require('./prices.seed.js').scan('"$PARAM1"')"
    ;;
'parse')
    echo "Tablename: $PARAM1"
    echo "Filename: $PARAM2"
    echo "Ticker: $PARAM3"

    if [ -z "$PARAM1" ] || [ -z "$PARAM2" ] || [ -z "$PARAM3" ]
    then
        printf "\nTwo paramters are required\n"
        printf "1. The path to the file\n"
        printf "2. The name of the table to insert the data\n"
        printf "3. The name of the ticker to be added to the db\n"
    else
        node -e "require('./prices.seed.js').parseCSV('"$PARAM1"', '"$PARAM2"', '"$PARAM3"')"
    fi
    ;;
*) echo "Signal number $1 is not processed"
   ;;
esac

echo "Total size of the table $PARAM1"
echo $(aws dynamodb describe-table --table-name $PARAM1 --endpoint http://localhost:8000 | grep TableSizeBytes)

